- Qwen/Qwen2-7B:
    per_device_train_batch_size: 1
    gradient_accumulation_steps: 8
    num_train_epochs: 1
    lora_rank: 4
    lora_alpha: 8
    lora_dropout: 0.1
    learning_rate: 1.0e-4
    warmup_steps: 20