- mistralai/Mistral-7B-Instruct-v0.3:
    per_device_train_batch_size: 1
    gradient_accumulation_steps: 8
    num_train_epochs: 3
    lora_rank: 16
    lora_alpha: 64
    lora_dropout: 0.1
    learning_rate: 1.0e-4
    warmup_steps: 20
- mistralai/Mistral-7B-Instruct-v0.3:
    per_device_train_batch_size: 1
    gradient_accumulation_steps: 8
    num_train_epochs: 3
    lora_rank: 64
    lora_alpha: 64
    lora_dropout: 0.1
    learning_rate: 1.0e-4
    warmup_steps: 20
- mistralai/Mistral-7B-Instruct-v0.3:
    per_device_train_batch_size: 1
    gradient_accumulation_steps: 8
    num_train_epochs: 3
    lora_rank: 16
    lora_alpha: 64
    lora_dropout: 0.05
    learning_rate: 1.0e-4
    warmup_steps: 20